# Generated by Django 4.2.25 on 2025-11-04 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('academic_calendar', models.CharField(blank=True, max_length=255)),
                ('program_type', models.CharField(blank=True, max_length=100)),
                ('minimum_gpa', models.CharField(blank=True, max_length=10)),
                ('language_prerequisite', models.CharField(blank=True, max_length=50)),
                ('additional_prerequisites', models.TextField(blank=True)),
                ('housing', models.TextField(blank=True)),
                ('main_page_url', models.URLField(blank=True)),
                ('homepage_url', models.URLField(blank=True)),
                ('budget_page_url', models.URLField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField()),
                ('order', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='programs.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BudgetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('total_estimated_cost', models.CharField(max_length=50)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_info', to='programs.program')),
            ],
            options={
                'unique_together': {('program', 'term', 'year')},
            },
        ),
    ]
