# Generated by Django 4.2.24 on 2025-11-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
