# Generated by Django 4.2.24 on 2025-11-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='continent',
            field=models.TextField(blank=True),
        ),
    ]
