# Generated by Django 4.2.24 on 2025-11-30 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alumni'),
        ('programs', '0003_program_continent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.alumni')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='programs.program')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
